- hosts: webservers
  tasks:

    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: "{{ansible_user}}"
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
